# Generated by Django 5.1.1 on 2024-11-22 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Observacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloVideo', models.CharField(blank=True, max_length=50)),
                ('urlVideo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='media')),
                ('nome', models.CharField(max_length=80)),
                ('naturalidade', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('publicoAlvo', models.CharField(max_length=50)),
                ('editora', models.CharField(blank=True, max_length=70)),
                ('resumo', models.TextField()),
                ('capaMaisLido01', models.ImageField(blank=True, upload_to='media')),
                ('capaMaisLido02', models.ImageField(blank=True, upload_to='media')),
                ('capaMaisLido03', models.ImageField(blank=True, upload_to='media')),
                ('maisLido', models.TextField(blank=True)),
                ('livros', models.TextField(blank=True)),
                ('generoAutor', models.ManyToManyField(to='app.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(blank=True, upload_to='media')),
                ('titulo', models.CharField(max_length=80)),
                ('lancamento', models.DateField()),
                ('nota', models.IntegerField()),
                ('resumo', models.TextField(blank=True)),
                ('introducao', models.TextField()),
                ('desenvolvimento', models.TextField()),
                ('conclusao', models.TextField()),
                ('imagem01', models.ImageField(blank=True, upload_to='media')),
                ('imagem02', models.ImageField(blank=True, upload_to='media')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.autor')),
                ('generoLivro', models.ManyToManyField(to='app.genero')),
                ('observacao', models.ManyToManyField(to='app.observacoes')),
                ('videos', models.ManyToManyField(blank=True, to='app.video')),
            ],
        ),
    ]
